name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - next
      - rc
      - next-rc-1
  workflow_dispatch:

jobs:
  test:
    name: Test / OS ${{ matrix.os }} / Node ${{ matrix.node }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['18']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Ensure build works
        run: |
          npm ci
          npm run build

      - name: Run tests
        run: |
          npm t
